
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          IFTTT_WEBHOOK_KEY: ${{ secret.IFTTT_WEBHOOK_KEY }}
        run: make test
